### ISSUE TITLE
Plugin library for original lineonetwo plugins

### ISSUE THREAD

**Issue by saqimtiaz** [linonetwo/wiki#17]
The plugin library at https://onetwo.ren/wiki/library/index.html includes plugins from other authors. 

I understand this is practical for you, but it's not a good idea for other users to use this and install plugins from non-official source.  You also have some interesting and unique plugins that you wrote yourself or modified from other users. If you could create a plugin library for these linonetwo plugins, that would be great for the TiddlyWiki community.

**Comment by linonetwo** [comment]
I was using this plugin library to recommend plugins for new TiddlyWiki users in China. But I think you are right, mixed content may cause confusion for other users.

The biggest reason is actually that, I'm now writing plugins directly in this repo, so things mixed with other plugins I'm using.
Maybe I can learn from kookma, he is writing plugins, using git submodules to combine all his plugin Github repos, and build them into a plugin library.

And I'm going to create some plugins for my new project, https://github.com/tiddly-gittly/TiddlyGit-Desktop/projects/2#column-9583988  , there will be more plugins, so I would definitely create a plugin library that includes only my original plugins.

**Comment by linonetwo** [comment]
I have one now! https://github.com/linonetwo/tiddlywiki-plugins
