### ISSUE TITLE
[Question] English version

### ISSUE THREAD

**Issue by kookma** [linonetwo/wiki#20]
This is a small question as there is no discussion page for this wiki!

You did a very nice work, but when I try and enjoy it! Is there any plan to publish an empty edition to be used by others?
Is there an English version?

Best wishes

**Comment by linonetwo** [comment]
Do you mean an English version of https://github.com/linonetwo/Tiddlywiki-NodeJS-Github-Template ?

It's just plain tw with a bunch of plugins, maybe it just needs an English language pack pre-bundled with it?

**Comment by linonetwo** [comment]
You can switch its language by edit the language field in the tiddlywiki.info I think.

**Comment by linonetwo** [comment]
And there is https://github.com/tiddly-gittly/TiddlyGit-Desktop/issues/132
